### ISSUE TITLE
二维码生成后会有白色的边框  这个边框能去掉么

### ISSUE THREAD

**Issue by gaiyonghuyichengxian** [demi520/wxapp-qrcode#11]

**Comment by demi520** [comment]
@gaiyonghuyichengxian您好， 什么白色边框？

**Comment by thaixp** [comment]
就是在生成二维码之后，会有一段外边框包住二维码，而我只想要二维码就好，请问怎么去掉那个框框

**Comment by chocking** [comment]
`去掉边框, api.draw =>`
`

        var that = this;
        ecclevel = ecc || ecclevel;
        canvas = canvas || _canvas;
        if (!canvas) {
            console.warn('No canvas provided to draw QR code in!')
            return;
        }

        var size = Math.min(cavW, cavH);
        str = that.utf16to8(str);//增加中文显示

        var frame = that.getFrame(str),
        // 组件中生成qrcode需要绑定this 
        ctx = wx.createCanvasContext(canvas,$this),
        // px = Math.round(size / (width + 8));
        px = Math.round(size / (width));
        //   var roundedSize = px * (width + 8),
        var roundedSize = px * (width),
        offset = Math.floor((size - roundedSize) / 2);
        size = roundedSize;
        //ctx.clearRect(0, 0, cavW, cavW);
        ctx.setFillStyle('#ffffff')
        ctx.fillRect(0, 0, cavW, cavW);
        ctx.setFillStyle('#000000');

        console.log('width : ',width)
        console.log('offset : ',offset)
        console.log('px : ',px)
        console.log('frame : ',frame)

        for (var i = 0; i < width; i++) {
            for (var j = 0; j < width; j++) {
                if (frame[j * width + i]) {
                // ctx.fillRect(px * (4 + i) + offset, px * (4 + j) + offset, px, px);
                ctx.fillRect(px * (i) + offset, px * (j) + offset, px, px);
                }
            }
        }
        ctx.draw();
    }
`

**Comment by thaixp** [comment]
谢谢
