### ISSUE TITLE
点击预览图片以后不显示怎么办。。。

### ISSUE THREAD

**Issue by guangxuan126** [demi520/wxapp-qrcode#3]

**Comment by demi520** [comment]
微信好像修复了安卓机器预览图片的bug吧，应该可以预览的，你在其他手机上试试，看有没有同样问题

**Comment by guangxuan126** [comment]
在ide里面和iPhone预览的时候还有问题的……

**Comment by demi520** [comment]
有段时间没有研究小程序了，这个写的比较早，之前wx.canvasToTempFilePath安卓机上有问题，iPhone上应该不会有问题的啊，我都测试过的，我load下来试试

**Comment by demi520** [comment]
现在wx.previewimage的图片路径不能用临时路径了 ，   http://blog.csdn.net/gao_xu_520/article/details/72724008

**Comment by guangxuan126** [comment]
那就是现在不能使用临时路径了吗？

**Comment by demi520** [comment]
应该是的
